{{- if and .Values.nodeExporter.enabled .Values.serviceAccounts.nodeExporter.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "prometheus.nodeExporter.labels" . | nindent 4 }}
  name: {{ template "prometheus.serviceAccountName.nodeExporter" . }}
{{- if .Values.serviceAccounts.nodeExporter.annotations }}
  annotations:
{{ toYaml .Values.serviceAccounts.nodeExporter.annotations | indent 4 }}
{{- end }}
{{- end -}}
